version: '3.0'
services:
  mongodb:
    image: mongo:latest
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/entrypoint/:/docker-entrypoint-initdb.d/
  backend:
    image: backend:latest
    build: './backend'
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    env_file: .env
  frontend:
    image: frontend:latest
    build: './frontend'
    ports:
      - "81:80"
    depends_on:
      - backend
